from soccerleague.businessobjects.competitors.competitor import Competitor
from soccerleague.businessobjects.competitors.soccerteam import SoccerTeam
from soccerleague.businessobjects.competitors.team import Team
